# get all persons
GET http://localhost:3003/api/persons

### get specific person
GET http://localhost:3003/api/persons/6412ba9c5b437d46d0c7c950


### delete person
DELETE http://localhost:3003/api/persons/6412ab9bc6fbf6da4c4c9652

### add new person
POST http://localhost:3003/api/persons HTTP/1.1
Content-Type: application/json

{ "name": "Arthur",
    "number": "048"
    }

### update person
PUT http://localhost:3003/api/persons/6412ba9c5b437d46d0c7c950
Content-Type: application/json

{   "name": "Arteo",
    "number": "048"
    }

### number of people in phone
GET http://localhost:3003/info
